# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 16:09
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('groups', '0003_auto_20160220_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
