# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_link_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
