# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20160221_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='media_type',
            field=models.CharField(choices=[('link', 'link'), ('article', 'article'), ('video', 'video')], default='link', max_length=255),
        ),
    ]
