# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 23:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0008_link_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='votes',
        ),
        migrations.AddField(
            model_name='link',
            name='votes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
